# Enable validating this file
version: ~> 1.0

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/dashboard


jobs:
  include:
    - install:
      - pip install -U platformio
      - platformio update
      script: ./build.sh
      name: "build examples"

